// Drizzle tables; drizzle-kit reads this file.
// The auth tables are generated by `npm run auth:generate`; never edit lib/auth-schema.ts by hand.
import { sql } from "drizzle-orm";
import {
  check,
  index,
  integer,
  sqliteTable,
  text,
} from "drizzle-orm/sqlite-core";
import { user } from "./auth-schema";

export * from "./auth-schema";

// Only lib/todo-service.ts reads or writes this table.
export const todos = sqliteTable(
  "todos",
  {
    id: text("id").primaryKey(),
    ownerId: text("owner_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    // `yyyy-mm-dd`; a date without time stays a string (see tech-docs/architecture.md).
    dueDate: text("due_date"),
    done: integer("done", { mode: "boolean" }).notNull().default(false),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
    completedAt: integer("completed_at", { mode: "timestamp_ms" }),
  },
  (table) => [
    index("todos_owner_id_idx").on(table.ownerId),
    check(
      "todos_completed_at_iff_done",
      sql`(${table.done} = 1) = (${table.completedAt} is not null)`,
    ),
  ],
);
